### PR TITLE
Fixes a potential typo

### PR DESCRIPTION
**Pull request by Vince-Smith**

### CODE REVIEW

**Comment by Vince-Smith** [comment]
I'm not sure if this is actually a typo or not 😆

**Comment by benjie** [comment]
I meant “use it for any situation where you need to name things”, i.e. feel encouraged to use it, use it a lot.

**Comment by Vince-Smith** [comment]
> I meant “use it for any situation where you need to name things”, i.e. feel encouraged to use it, use it a lot.

Thanks @benjie! Had a 50/50 chance of being right 😆 

I've updated the documentation based on your comment to try to prevent future confusion.

**Review by benjie — APPROVED** [review]
Thanks!

**Pull request merged**
